"""migration 3

Revision ID: 25ed27b2cf1d
Revises: 0c26f13be2dc
Create Date: 2026-02-13 17:16:24.193011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ed27b2cf1d'
down_revision: Union[str, Sequence[str], None] = '0c26f13be2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_from_email'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_received_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_workspace_id'), table_name='email_messages')
    op.drop_constraint(op.f('uq_email_gmail_msg'), 'email_messages', type_='unique')
    op.drop_index(op.f('ix_gmail_integrations_workspace_id'), table_name='gmail_integrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gmail_integrations_workspace_id'), 'gmail_integrations', ['workspace_id'], unique=False)
    op.create_unique_constraint(op.f('uq_email_gmail_msg'), 'email_messages', ['workspace_id', 'gmail_message_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_email_messages_workspace_id'), 'email_messages', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_email_messages_received_at'), 'email_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_thread_id'), 'email_messages', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_message_id'), 'email_messages', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_from_email'), 'email_messages', ['from_email'], unique=False)
    # ### end Alembic commands ###
