"""added dashboard

Revision ID: 47c6f9c7323b
Revises: 9aed409e2283
Create Date: 2026-02-13 10:25:48.574220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c6f9c7323b'
down_revision: Union[str, Sequence[str], None] = '9aed409e2283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_booking_type_id', 'bookings', ['booking_type_id'], unique=False)
    op.create_index('ix_bookings_contact_id', 'bookings', ['contact_id'], unique=False)
    op.create_index('ix_bookings_workspace_created_at', 'bookings', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_bookings_workspace_start_time', 'bookings', ['workspace_id', 'start_time'], unique=False)
    op.create_index('ix_bookings_workspace_status', 'bookings', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_conversations_contact_id', 'conversations', ['contact_id'], unique=False)
    op.create_index('ix_conversations_workspace_status', 'conversations', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_form_submissions_booking_id', 'form_submissions', ['booking_id'], unique=False)
    op.create_index('ix_form_submissions_created_at', 'form_submissions', ['created_at'], unique=False)
    op.create_index('ix_form_submissions_status', 'form_submissions', ['status'], unique=False)
    op.create_index('ix_inventory_items_workspace_quantity', 'inventory_items', ['workspace_id', 'quantity'], unique=False)
    op.create_index('ix_inventory_usage_booking_id', 'inventory_usage', ['booking_id'], unique=False)
    op.create_index('ix_inventory_usage_workspace_created', 'inventory_usage', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_usage_workspace_created', table_name='inventory_usage')
    op.drop_index('ix_inventory_usage_booking_id', table_name='inventory_usage')
    op.drop_index('ix_inventory_items_workspace_quantity', table_name='inventory_items')
    op.drop_index('ix_form_submissions_status', table_name='form_submissions')
    op.drop_index('ix_form_submissions_created_at', table_name='form_submissions')
    op.drop_index('ix_form_submissions_booking_id', table_name='form_submissions')
    op.drop_index('ix_conversations_workspace_status', table_name='conversations')
    op.drop_index('ix_conversations_contact_id', table_name='conversations')
    op.drop_index('ix_bookings_workspace_status', table_name='bookings')
    op.drop_index('ix_bookings_workspace_start_time', table_name='bookings')
    op.drop_index('ix_bookings_workspace_created_at', table_name='bookings')
    op.drop_index('ix_bookings_contact_id', table_name='bookings')
    op.drop_index('ix_bookings_booking_type_id', table_name='bookings')
    # ### end Alembic commands ###
