"""fixed some stuff

Revision ID: 56fd328989c3
Revises: d0f406be640b
Create Date: 2026-02-12 15:28:48.111163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fd328989c3'
down_revision: Union[str, Sequence[str], None] = 'd0f406be640b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_logs', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('communication_logs', sa.Column('sent_by_staff', sa.Boolean(), nullable=True))
    op.add_column('communication_logs', sa.Column('automated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communication_logs', 'automated')
    op.drop_column('communication_logs', 'sent_by_staff')
    op.drop_column('communication_logs', 'message')
    # ### end Alembic commands ###
