"""migration 3

Revision ID: 582fda9d8dba
Revises: a72c2580e2a8
Create Date: 2026-02-13 17:08:36.957054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582fda9d8dba'
down_revision: Union[str, Sequence[str], None] = 'a72c2580e2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_booking_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_workspace_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_integrations_workspace_id'), table_name='calendar_integrations')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_workspace_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_submitted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_leads_submitted_at'), 'leads', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_workspace_id'), 'lead_activities', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_calendar_integrations_workspace_id'), 'calendar_integrations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_booking_id'), 'calendar_events', ['booking_id'], unique=False)
    # ### end Alembic commands ###
