"""fixing

Revision ID: b43a64d69fe0
Revises: fa84cbfee96e
Create Date: 2026-02-12 23:14:23.422386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43a64d69fe0'
down_revision: Union[str, Sequence[str], None] = 'fa84cbfee96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_forms', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_forms', 'status')
    # ### end Alembic commands ###
