"""fixing

Revision ID: fa84cbfee96e
Revises: e8fa8e7c634b
Create Date: 2026-02-12 23:05:56.614849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa84cbfee96e'
down_revision: Union[str, Sequence[str], None] = 'e8fa8e7c634b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_forms', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_forms', 'description')
    # ### end Alembic commands ###
